### ISSUE TITLE
Recipient

### ISSUE THREAD

**Issue by noldan** [svv2014/OctoPrint-xMatters-integration#2]
What is the recipient ? I tried with the email used for xMatters ans ÀI did'nt received any notification.

OctoPapy

**Comment by svv2014** [comment]
So, In xMatters you should open "users" tab, find your user and use value from "user id" column.

**Comment by svv2014** [comment]
Ultimately you can open your profile in `xMatters` and find `user id`. Use `user id` in recipient field.
