### ISSUE TITLE
configuration screen blank

### ISSUE THREAD

**Issue by DotNetRob** [svv2014/OctoPrint-xMatters-integration#3]
Configuration screen is blank, installed via repository and rebooted the server.  Tried uninstalling, rebooting, reinstalling, rebooting again, but config screen is still blank.  Checked the logs but didn't see anything.  Octoprint is on the latest version, just setup a few days ago. 

![xmatter](https://user-images.githubusercontent.com/2489404/53753167-33f0e880-3e76-11e9-8eda-3db24180e98b.PNG)

**Comment by svv2014** [comment]
Huh, full restart usually helps...

**Comment by svv2014** [comment]
There is some issue with browser cache I've seen from time to time. Try install, close page, reboot, open new page, maybe open in incognito mode if you are using chrome. If this will not help I'll try to dig deeper.

**Comment by DotNetRob** [comment]
I normally use firefox, but opened it in chrome incognito mode and still have a blank screen.  Was using the System Reboot in the top menu for reboots, but i just did the octoprint restart this time and the screen now comes up.   I would think rebooting the system would reboot octoprint too...
